before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: yEH6wDwij3Gr864g0nbrOkEGjNhw1J3/RsujVSikRv+v2h+EG2xNlsus+ssotZR1j1RJ16Vyl6iA1c7MbH3pO7RCYH3lwuqyMn3ihuMq+zPTaDwWVzKYQYw1XxExQ6WfZKs8M1zi35cMicKzvOIPKCZJ52OZbbgJ5epZkGMHwu3NfrjJLPv2eywasi/CuuG3jPfxGN6YMSp3D6FHCP52icfEcCH08IgbqeQhh2AKCkGH199YE6W44ThU/32vqZvLL6aaU1ZIW7iTsClJblN9FpgG5JQ8qPwhmBejSJHb4micNxVWsZcF+Cn50eew3Lb9ZvaQUJzCnBxTbhSZb2JeKr12HRZsbhlmstOCugSTuYMkv6qkVFcmkTw4vFlbyW8sycBA2EDIQMCvcnTU1vwZUN+agPrUa9qCOqag7H2govdzkkqzMAoWKT5MTZdOo/axnN8LyJ8MBXNsiAXDmhuCYcMCf4qUkXmvZTuB4Wfc0e+WjuCiy3y+HuoIIKVdc+/Qz/An6jVKi6MZwUpo2ry0h5u2UzX5mlw2iJ2xxq1u1EyIRHHFmrzlO958beG7nQ3y9kTbkLMFtDuLKYCYnKXJQuXUX2l0cqZ6o9mZj+ZSzs+xHKDMCbUSuxfYW/V7GXKNIt2dwtMU148HNN0hpZ0lRC8uk0kYmAYVkHYUVPx4KQY= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
